### ISSUE TITLE
reproduction results

### ISSUE THREAD

**Issue by qhmiao** [leo-yangli/VB-LoRA#1]
Hi,

Thank you for sharing your work! I ran your code on the CoLA dataset without modifying any settings. However, I noticed that my reproduction results differ slightly from the paper. Specifically:

The paper reports a result of 64 ± 1.4 on CoLA.
My last checkpoint achieves 60.314, while the best checkpoint reaches 64.6.
Could you clarify if the reported result in the paper corresponds to the best checkpoint or the last checkpoint?

Thank you for your help!
![图片](https://github.com/user-attachments/assets/346bf1a9-4146-475b-bfb3-8c43bf58049c)

**Comment by leo-yangli** [comment]
Thank you for your interest in our work! Following the experiment settings in LoRA, we report the median performance over 5 random seeds for all GLUE benchmark experiments, and the result for each run is based on the best-performing epoch.

**Comment by qhmiao** [comment]
thank you!
